import {Cloneable} from '@enonic/lib-admin-ui/Cloneable';
import {Equitable} from '@enonic/lib-admin-ui/Equitable';
import {Form} from '@enonic/lib-admin-ui/form/Form';
import {ObjectHelper} from '@enonic/lib-admin-ui/ObjectHelper';
import {DescriptorKey} from './DescriptorKey';
import {DescriptorName} from './DescriptorName';
import {RegionDescriptor} from './RegionDescriptor';
import {DescriptorJson} from './DescriptorJson';
import {ComponentType} from './region/ComponentType';

export class Descriptor
    implements Cloneable, Equitable {

    private readonly key: DescriptorKey;

    private readonly name: DescriptorName;

    private readonly displayName: string;

    private readonly description: string;

    private readonly config: Form;

    private readonly icon: string;

    private readonly regions: RegionDescriptor[];

    private readonly autoGenerated: boolean;

    private iconCls: string;

    private componentType: ComponentType;

    constructor(builder: DescriptorBuilder) {
        this.name = builder.name;
        this.key = builder.key;
        this.displayName = builder.displayName;
        this.description = builder.description;
        this.config = builder.config;
        this.icon = builder.icon;
        this.iconCls = builder.iconCls;
        this.regions = builder.regions;
        this.autoGenerated = builder.autoGenerated;
    }

    static fromJson(json: DescriptorJson): Descriptor {
        return DescriptorBuilder.fromJson(json).build();
    }

    getKey(): DescriptorKey {
        return this.key;
    }

    getName(): DescriptorName {
        return this.name;
    }

    getDisplayName(): string {
        return this.displayName;
    }

    getDescription(): string {
        return this.description;
    }

    getConfig(): Form {
        return this.config;
    }

    setComponentType(componentType: ComponentType) {
        this.componentType = componentType;
        return this;
    }

    getComponentType(): ComponentType {
        return this.componentType;
    }

    getIconCls(): string {
        return this.iconCls ? this.iconCls : this.componentType.getIconCls();
    }

    getIcon(): string {
        return this.icon;
    }

    getRegions(): RegionDescriptor[] {
        return this.regions;
    }

    isAutoGenerated(): boolean {
        return this.autoGenerated;
    }

    clone(): Descriptor {
        return new DescriptorBuilder(this).build();
    }

    equals(o: Equitable): boolean {
        if (!ObjectHelper.iFrameSafeInstanceOf(o, Descriptor)) {
            return false;
        }

        let other = o as Descriptor;

        return this.name.toString() === other.getName().toString() &&
                this.componentType === other.getComponentType() &&
                this.key.equals(other.getKey()) &&
                this.displayName === other.getDisplayName() &&
                this.description === other.getDescription() &&
                this.autoGenerated === other.isAutoGenerated() &&
                this.config.equals(other.getConfig()) &&
                ObjectHelper.arrayEquals(this.regions, other.getRegions());
    }
}

export class DescriptorBuilder {

    key: DescriptorKey;

    name: DescriptorName;

    displayName: string;

    description: string;

    config: Form;

    icon: string;

    iconCls: string;

    regions: RegionDescriptor[] = [];

    autoGenerated: boolean;

    constructor(source?: Descriptor) {
        if (source) {
            this.key = source.getKey();
            this.name = source.getName();
            this.displayName = source.getDisplayName();
            this.description = source.getDescription();
            this.config = source.getConfig();
            this.icon = source.getIcon();
            this.regions = source.getRegions();
        }
    }

    static fromJson(json: DescriptorJson): DescriptorBuilder {
        const descriptorKey: DescriptorKey = DescriptorKey.fromString(json.key);
        return new DescriptorBuilder()
            .setName(new DescriptorName(json.name))
            .setDisplayName(json.displayName)
            .setDescription(json.description)
            .setConfig(json.config != null ? Form.fromJson(json.config, descriptorKey.getApplicationKey()) : null)
            .setIcon(json.icon)
            .setKey(descriptorKey)
            .setAutoGenerated(json.autoGenerated)
            .setRegions(json.regions?.map(regionJson => RegionDescriptor.fromJson(regionJson)));
    }

    public setKey(value: DescriptorKey): this {
        this.key = value;
        return this;
    }

    public setName(value: DescriptorName): this {
        this.name = value;
        return this;
    }

    public setDisplayName(value: string): this {
        this.displayName = value;
        return this;
    }

    public setDescription(value: string): this {
        this.description = value;
        return this;
    }

    public setConfig(value: Form): this {
        this.config = value;
        return this;
    }

    public setIcon(value: string): this {
        this.icon = value;
        return this;
    }

    public setIconCls(iconCls: string) {
        this.iconCls = iconCls;
        return this;
    }

    public setRegions(value: RegionDescriptor[]): this {
        this.regions = value;
        return this;
    }

    setAutoGenerated(value: boolean): this {
        this.autoGenerated = value;
        return this;
    }

    public build(): Descriptor {
        return new Descriptor(this);
    }
}
