import { type PropertyArrayJson } from '@enonic/lib-admin-ui/data/PropertyArrayJson';
import { PropertyTree } from '@enonic/lib-admin-ui/data/PropertyTree';
import { initBuiltInTypes } from '@enonic/lib-admin-ui/form2';
import { ContentTypeName } from '@enonic/lib-admin-ui/schema/content/ContentTypeName';
import Q from 'q';
import { afterEach, beforeAll, beforeEach, describe, expect, it, vi } from 'vitest';
import { ContentBuilder, type Content } from '../content/Content';
import { ContentId } from '../content/ContentId';
import { ContentName } from '../content/ContentName';
import { Descriptor } from '../page/Descriptor';
import { type DescriptorJson } from '../page/DescriptorJson';
import { DescriptorKey } from '../page/DescriptorKey';
import { type Page, PageBuilder } from '../page/Page';
import { PageTemplateKey } from '../page/PageTemplateKey';
import { PartComponent, PartComponentBuilder } from '../page/region/PartComponent';
import { Region } from '../page/region/Region';
import { Regions } from '../page/region/Regions';
import { GetComponentDescriptorRequest } from '../resource/GetComponentDescriptorRequest';
import { type ContentWizardPanel } from './ContentWizardPanel';
import { CreatePageRequest } from './CreatePageRequest';
import { RoutineContext } from './Flow';
import { UpdatePersistedContentRoutine } from './UpdatePersistedContentRoutine';

const PART_KEY = 'com.enonic.app.superhero:latest-comments';
const CONTROLLER_KEY = 'com.enonic.app.superhero:default';
const UNKNOWN_PART_KEY = 'com.enonic.app.superhero:removed-part';

type PartJson = { descriptor: string; config: PropertyArrayJson[] };
type RegionJson = { name: string; components: { PartComponent?: PartJson }[] };
type PageParams = { regions: RegionJson[] | null; fragment: { PartComponent?: PartJson } | null };

function inputJson(name: string, inputType: string): object {
    return {
        Input: { name, inputType, label: name, occurrences: { minimum: 0, maximum: 1 }, config: {}, helpText: '' },
    };
}

function descriptorOf(key: string, formItems: object[], regions: { name: string }[] = []): Descriptor {
    return Descriptor.fromJson({
        key,
        name: DescriptorKey.fromString(key).getName(),
        displayName: key,
        description: '',
        config: { formItems },
        regions,
        autoGenerated: false,
    } as unknown as DescriptorJson);
}

const descriptors: Record<string, Descriptor> = {
    [PART_KEY]: descriptorOf(PART_KEY, [inputJson('headline', 'TextLine'), inputJson('size', 'Long')]),
    [CONTROLLER_KEY]: descriptorOf(CONTROLLER_KEY, [], [{ name: 'main' }]),
};

function stringArray(name: string, value: string): PropertyArrayJson {
    return { name, type: 'String', values: [{ v: value }] };
}

function latestCommentsPart(descriptorKey: string = PART_KEY): PartComponent {
    return new PartComponentBuilder()
        .setDescriptor(DescriptorKey.fromString(descriptorKey))
        .setConfig(PropertyTree.fromJson([stringArray('headline', 'Latest comments'), stringArray('size', '5')]))
        .build();
}

function customizedPage(part: PartComponent): Page {
    const region = Region.create().setName('main').addComponent(part).build();
    return new PageBuilder()
        .setController(DescriptorKey.fromString(CONTROLLER_KEY))
        .setRegions(Regions.create().addRegion(region).build())
        .build();
}

function createContent(page: Page | null): Content {
    const builder = new ContentBuilder();
    builder.setId('content-id');
    builder.setContentId(new ContentId('content-id'));
    builder.setName(new ContentName('post'));
    builder.setType(new ContentTypeName('com.enonic.app.superhero:post'));
    builder.setDisplayName('Post');
    builder.setData(new PropertyTree());
    builder.setPage(page);
    return builder.build();
}

async function savePage(viewedPage: Page): Promise<PageParams> {
    const persistedContent = createContent(null);
    const viewedContent = createContent(viewedPage);
    let sentParams: PageParams = null;

    vi.spyOn(CreatePageRequest.prototype, 'sendAndParse').mockImplementation(function (this: CreatePageRequest) {
        sentParams = this.getParams() as PageParams;
        return Q(viewedContent);
    });

    const routine = new UpdatePersistedContentRoutine({} as ContentWizardPanel, persistedContent, viewedContent);
    const context = new RoutineContext();
    context.content = persistedContent;

    await (routine as unknown as { doHandlePage: (context: RoutineContext) => Q.Promise<void> }).doHandlePage(context);

    return sentParams;
}

function partConfig(params: PageParams): PropertyArrayJson[] {
    return params.regions[0].components[0].PartComponent.config;
}

describe('UpdatePersistedContentRoutine page save', () => {
    beforeAll(() => {
        initBuiltInTypes();
    });

    beforeEach(() => {
        vi.spyOn(GetComponentDescriptorRequest.prototype, 'sendAndParse').mockImplementation(
            function (this: GetComponentDescriptorRequest) {
                const key = (this as unknown as { descriptorKey: string }).descriptorKey;
                const descriptor = descriptors[key];
                return descriptor ? Q(descriptor) : Q.reject<Descriptor>(new Error(`No descriptor ${key}`));
            },
        );
    });

    afterEach(() => {
        vi.restoreAllMocks();
    });

    it('should send component config values typed by the descriptor inputs when a customized page is saved', async () => {
        const params = await savePage(customizedPage(latestCommentsPart()));

        expect(partConfig(params)).toEqual([
            { name: 'headline', type: 'String', values: [{ v: 'Latest comments' }] },
            { name: 'size', type: 'Long', values: [{ v: 5 }] },
        ]);
    });

    it('should save a template-only page without regions', async () => {
        const params = await savePage(new PageBuilder().setTemplate(PageTemplateKey.fromString('template-id')).build());

        expect(params).not.toBeNull();
        expect(params.regions).toBeNull();
        expect(params.fragment).toBeNull();
    });

    it('should normalize the config of a standalone fragment', async () => {
        const params = await savePage(new PageBuilder().setFragment(latestCommentsPart()).build());

        expect(params.regions).toBeNull();
        expect(params.fragment.PartComponent.config).toEqual([
            { name: 'headline', type: 'String', values: [{ v: 'Latest comments' }] },
            { name: 'size', type: 'Long', values: [{ v: 5 }] },
        ]);
    });

    it('should leave the config untouched when the descriptor cannot be loaded', async () => {
        const params = await savePage(customizedPage(latestCommentsPart(UNKNOWN_PART_KEY)));

        expect(partConfig(params)).toEqual([
            { name: 'headline', type: 'String', values: [{ v: 'Latest comments' }] },
            { name: 'size', type: 'String', values: [{ v: '5' }] },
        ]);
    });
});
