= Content Studio documentation
:toc: right
:imagesdir: images

Enonic XP's Content Management interface

NOTE: Content Studio can be installed from https://market.enonic.com/vendors/enonic/content-studio[Enonic Market]

== Intro videos

We have compiled a page packed with short videos demonstrating Content Studio's features and capabilities. https://www.enonic.com/resources/content-studio-videos[Check it out].


== Overview

Content Studio provide editors with an efficient way of creating and curating content without technical skills.

Content is organized within <<projects#,Content Projects>>. Content can be re-used, localized or augmented across different projects through a feature called <<layers#, content layering>>.

Editors will commonly use the <<navigator#,navigator panel>> to browse, search and perform actions on one or more items.

The <<editor#, content editor>> offers a consistent and intuitive interface for editing and previewing your content.

== Go beyond

Content Studio is free and open source, but also highly extendable. A subscription gives you access to licensed applications that extend Content Studio with advanced capabilities like an <<ai#, AI assistant>>, the <<archive#, archive browser>> and <<layers#, automated translations>>.

== Browser support

Content Studio works in all modern browsers.  We are explicitly testing it and supporting it for the latest versions of Google Chrome, Apple Safari, Mozilla Firefox and Microsoft Edge.


== Release notes

Curious about what is new in this version? Check out the <<release#,release notes>>.
