= Content Studio documentation
:toc: right
:imagesdir: images

Content Management interface for Enonic XP

== Introduction

NOTE: *Install?* Content Studio is available as an application for Enonic XP, and can be installed from https://market.enonic.com/vendors/enonic/content-studio[Enonic Market]

== Overview

Content Studio provides editors with an efficient way of creating, and curating content without technical skills.

Content is organized within <<projects#,Content Projects>>. Content can be re-used, localized or augmented across different projects through a feature called <<layers#, content layering>>.

Editors will commonly use the <<navigator#,navigator panel>> to browse, search and perform actions on one or more items.

Use documentation menu for more details

== Subscribe for more

Content Studio is open source and free for everyone. Customers with a valid Enonic subscription additionally get access to Enonic licensed applications. Several of these add advanced capabilities to Content Studio, such as the <<archive#, archive browser>> and <<ai#, AI assistant>>. 

Appliccable features are marked with "Subscription required" thoughout the documentation.

Visit Enonic Market for the https://market.enonic.com/licensed[complete list of licensed applications]


== Browser support

Content Studio works in all modern browsers.  We are explicitly testing it and supporting it for the latest versions of Google Chrome, Apple Safari, Mozilla Firefox and Microsoft Edge.


== Release notes

Curious about what is new in this version? Check out the <<release#,release notes>>.
