= Content Studio documentation
:toc: right
:imagesdir: images

Content Studio is the ultimate CMS interface for Enonic XP

== Introduction

NOTE: *Install?* Content Studio is available as an application for Enonic XP, and can be installed from https://market.enonic.com[Enonic Market]


== Overview

Content Studio provides editors with an efficient way of creating, and curating content without technical skills.
A core concept is that any content item has a specific <<content-types#,Content type>>.

A set of standard content types come with the system, but the real benefit lies in custom defined content types.
Custom content types are defined by developers, and provided through apps.

Editors will commonly use the <<navigator#,navigator panel>> to browse, search and perform actions on one or more items.
<<issues#,Issues>> can be created and assigned to users of Content Studio in order to get stuff done, and assist with workflow related tasks, such as getting an item published.

== Browser support

Content Studio may be ran in all modern browsers.  We are explicitly testing it and supporting it for the latest versions of Chrome, Safari, Firefox, Edge and Internet Explorer.

== Release notes

Curious about whats new in this version? Check out the <<release#,release notes>>.
