= Release Notes
:toc: right
:imagesdir: release/images

TIP: Release Notes for Content Studio 3.x can be found https://developer.enonic.com/docs/content-studio/3.x/release[here]

== Content Studio 4

IMPORTANT: Content Studio 4.0 requires XP 7.8.0 or higher.

=== Image Component is deprecated

Image Component has been deprecated in favour of <<editor/component-types#text_component, `Text Component`>> which can be used for embedding
images and has a richer UI than Image Component used to have. Existing image components on your page will continue working, but you won't be able to add a new one.

== Upgrade notes for Content Studio 4.x

=== Admin API

Admin API has been moved from XP core to Content Studio and starting from version 4.0.0 resides directly in the Content Studio app. This will
help us release Content Studio without having to change XP and release a new version of the platform. URLs of Admin API have been changed as well.
Admin API was never intended for external use, but beware of that if you had any custom integration with Content Studio's Admin API then
this will stop working from version 4.0. As this migration affected XP as well, Content Studio 4.x requires XP 7.8.0 or higher.
