import {NamePrettyfier} from '@enonic/lib-admin-ui/NamePrettyfier';
import {map} from 'nanostores';
import {ContentUnnamed} from '../../../app/content/ContentUnnamed';
import type {PublishStatus} from '../../../app/publish/PublishStatus';
import type {WizardToolbarCollaborator, WizardToolbarStore} from './wizardToolbar.types';
import {$wizardContentState, $wizardDraftDisplayName, $wizardDraftName, $wizardPersistedDisplayName, $wizardPersistedName, setDraftName} from './wizardContent.store';
import {ContentName} from '../../../app/content/ContentName';

const createInitialState = (): WizardToolbarStore => ({
    projectLabel: '',
    projectName: '',
    projectLanguage: '',
    projectHasIcon: false,
    collaborators: [],
    publishStatus: null,
    contentPath: '',
    canRenameContentPath: false,
    isContentOnline: false,
    contentState: null,
    isLayerProject: false,
});

export const $wizardToolbar = map<WizardToolbarStore>(createInitialState());

function prettifyName(displayName: string): string {
    return NamePrettyfier.prettify(displayName);
}

function isNameAutoGenerated(name: string, displayName: string): boolean {
    if (!name) {
        return true;
    }

    const nameLower = name.toLowerCase();

    return nameLower === displayName.toLowerCase() || nameLower === prettifyName(displayName).toLowerCase();
}

function normalizeContentPath(name: string): string {
    return name.startsWith(ContentUnnamed.UNNAMED_PREFIX) ? '' : name;
}

let previousDisplayName: string | undefined;

$wizardDraftDisplayName.subscribe((displayName) => {
    if ($wizardToolbar.get().isContentOnline || previousDisplayName === undefined || displayName === previousDisplayName) {
        previousDisplayName = displayName;
        return;
    }

    const currentName = $wizardDraftName.get()?.toString() || '';

    if (isNameAutoGenerated(currentName, previousDisplayName)) {
        if (displayName === $wizardPersistedDisplayName.get()) {
            const persistedName = $wizardPersistedName.get();
            if (persistedName) {
                setDraftName(persistedName);
                $wizardToolbar.setKey('contentPath', normalizeContentPath(persistedName.toString()));
            }
        } else {
            const newName = prettifyName(displayName);
            const newContentName = newName ? new ContentName(newName) : ContentUnnamed.newUnnamed();
            setDraftName(newContentName);
            $wizardToolbar.setKey('contentPath', normalizeContentPath(newName));
        }
    }

    previousDisplayName = displayName;
});

$wizardDraftName.subscribe((name) => {
    const nameStr = name?.toString() || '';
    $wizardToolbar.setKey('contentPath', normalizeContentPath(nameStr));
});

$wizardContentState.subscribe((contentState) => {
    $wizardToolbar.setKey('contentState', contentState);
});

export function setWizardToolbarProjectLabel(projectLabel: string): void {
    $wizardToolbar.setKey('projectLabel', projectLabel);
}

export function setWizardToolbarProjectInfo(projectName: string, projectLanguage: string, projectHasIcon: boolean): void {
    $wizardToolbar.setKey('projectName', projectName);
    $wizardToolbar.setKey('projectLanguage', projectLanguage);
    $wizardToolbar.setKey('projectHasIcon', projectHasIcon);
}

export function setWizardToolbarCollaborators(collaborators: WizardToolbarCollaborator[]): void {
    $wizardToolbar.setKey('collaborators', collaborators);
}

export function setWizardToolbarPublishStatus(publishStatus: PublishStatus | null): void {
    $wizardToolbar.setKey('publishStatus', publishStatus);
}

export function setWizardToolbarContentPath(contentPath: string): void {
    $wizardToolbar.setKey('contentPath', contentPath);
}

export function setWizardToolbarCanRenameContentPath(canRenameContentPath: boolean): void {
    $wizardToolbar.setKey('canRenameContentPath', canRenameContentPath);
}

export function setWizardToolbarIsContentOnline(isContentOnline: boolean): void {
    $wizardToolbar.setKey('isContentOnline', isContentOnline);
}

export function setWizardToolbarIsLayerProject(isLayerProject: boolean): void {
    $wizardToolbar.setKey('isLayerProject', isLayerProject);
}

export function resetWizardToolbar(): void {
    previousDisplayName = $wizardDraftDisplayName.get();
    $wizardToolbar.set({
        ...createInitialState(),
        contentState: $wizardContentState.get(),
    });
}
