import {Name} from '@enonic/lib-admin-ui/Name';
import {NamePrettyfier} from '@enonic/lib-admin-ui/NamePrettyfier';
import {map} from 'nanostores';
import {ContentName} from '../../../app/content/ContentName';
import {ContentUnnamed} from '../../../app/content/ContentUnnamed';
import type {PublishStatus} from '../../../app/publish/PublishStatus';
import {$config} from './config.store';
import {
    $contentType,
    $wizardContentState,
    $wizardDraftDisplayName,
    $wizardDraftName,
    $wizardPersistedDisplayName,
    $wizardPersistedName,
    setDraftName,
} from './wizardContent.store';
import type {WizardToolbarCollaborator, WizardToolbarStore} from './wizardToolbar.types';

const createInitialState = (): WizardToolbarStore => ({
    projectLabel: '',
    projectName: '',
    projectLanguage: '',
    projectHasIcon: false,
    collaborators: [],
    publishStatus: null,
    contentName: '',
    contentParentPath: '',
    canRenameContentPath: false,
    isContentOnline: false,
    contentState: null,
    isLayerProject: false,
    isContentInherited: false,
    isContentDataInherited: false,
});

export const $wizardToolbar = map<WizardToolbarStore>(createInitialState());

function isSimplifiedNameGeneration(): boolean {
    const isMedia = $contentType.get()?.getContentTypeName()?.isDescendantOfMedia() ?? false;
    return isMedia || !$config.get().allowPathTransliteration;
}

function prettifyName(displayName: string): string {
    if (isSimplifiedNameGeneration()) {
        return displayName.replace(Name.SIMPLIFIED_FORBIDDEN_CHARS, '').toLowerCase();
    }

    return NamePrettyfier.prettify(displayName);
}

function isNameAutoGenerated(name: string, displayName: string): boolean {
    if (!name) {
        return true;
    }

    const nameLower = name.toLowerCase();

    return nameLower === displayName.toLowerCase() || nameLower === prettifyName(displayName).toLowerCase();
}

function normalizeContentName(name: string): string {
    return name.startsWith(ContentUnnamed.UNNAMED_PREFIX) ? '' : name;
}

let previousDisplayName: string | undefined;

$wizardDraftDisplayName.subscribe(displayName => {
    if (
        $wizardToolbar.get().isContentOnline ||
        previousDisplayName === undefined ||
        displayName === previousDisplayName
    ) {
        previousDisplayName = displayName;
        return;
    }

    const currentName = $wizardDraftName.get()?.toString() || '';

    if (isNameAutoGenerated(currentName, previousDisplayName)) {
        if (displayName === $wizardPersistedDisplayName.get()) {
            const persistedName = $wizardPersistedName.get();
            if (persistedName) {
                setDraftName(persistedName);
                $wizardToolbar.setKey('contentName', normalizeContentName(persistedName.toString()));
            }
        } else {
            const newName = prettifyName(displayName);
            const newContentName = newName ? new ContentName(newName) : ContentUnnamed.newUnnamed();
            setDraftName(newContentName);
            $wizardToolbar.setKey('contentName', normalizeContentName(newName));
        }
    }

    previousDisplayName = displayName;
});

$wizardDraftName.subscribe(name => {
    const nameStr = name?.toString() || '';
    $wizardToolbar.setKey('contentName', normalizeContentName(nameStr));
});

$wizardContentState.subscribe(contentState => {
    $wizardToolbar.setKey('contentState', contentState);
});

export function setWizardToolbarProjectLabel(projectLabel: string): void {
    $wizardToolbar.setKey('projectLabel', projectLabel);
}

export function setWizardToolbarProjectInfo(
    projectName: string,
    projectLanguage: string,
    projectHasIcon: boolean,
): void {
    $wizardToolbar.setKey('projectName', projectName);
    $wizardToolbar.setKey('projectLanguage', projectLanguage);
    $wizardToolbar.setKey('projectHasIcon', projectHasIcon);
}

export function setWizardToolbarCollaborators(collaborators: WizardToolbarCollaborator[]): void {
    $wizardToolbar.setKey('collaborators', collaborators);
}

export function setWizardToolbarPublishStatus(publishStatus: PublishStatus | null): void {
    $wizardToolbar.setKey('publishStatus', publishStatus);
}

export function setWizardToolbarContentName(contentName: string): void {
    $wizardToolbar.setKey('contentName', contentName);
}

export function setWizardToolbarContentParentPath(contentParentPath: string): void {
    $wizardToolbar.setKey('contentParentPath', contentParentPath);
}

export function setWizardToolbarCanRenameContentPath(canRenameContentPath: boolean): void {
    $wizardToolbar.setKey('canRenameContentPath', canRenameContentPath);
}

export function setWizardToolbarIsContentOnline(isContentOnline: boolean): void {
    $wizardToolbar.setKey('isContentOnline', isContentOnline);
}

export function setWizardToolbarIsLayerProject(isLayerProject: boolean): void {
    $wizardToolbar.setKey('isLayerProject', isLayerProject);
}

export function setWizardToolbarContentInheritance(isInherited: boolean, isDataInherited: boolean): void {
    $wizardToolbar.setKey('isContentInherited', isInherited);
    $wizardToolbar.setKey('isContentDataInherited', isDataInherited);
}

export function resetWizardToolbar(): void {
    previousDisplayName = $wizardDraftDisplayName.get();
    $wizardToolbar.set({
        ...createInitialState(),
        contentState: $wizardContentState.get(),
    });
}
